version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - apt update -y
      - apt install nginx -y
      - echo NGINX installation complete

  build:
    commands:
      - echo Build started on `date`
      - echo Copying index.html to NGINX web folder
      - cp index.html /var/www/html/

  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - /var/www/html/index.html
    - buildspec.yml
    - scripts/*
    - appspec.yml
